# Generated by Django 5.2.5 on 2025-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('admissao', models.DateField()),
                ('demissao', models.DateField()),
                ('area_atuacao', models.CharField(max_length=100)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fardamento', models.BooleanField(default=False)),
                ('chip_voz', models.BooleanField(default=False)),
                ('chip_dados', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('carregador_tablet', models.BooleanField(default=False)),
                ('fone_tablet', models.BooleanField(default=False)),
                ('catalogo', models.BooleanField(default=False)),
                ('bloco_pedido', models.BooleanField(default=False)),
                ('carta_pedido_demissao', models.BooleanField(default=False)),
                ('relatorio_inadimplencia', models.BooleanField(default=False)),
                ('substituto', models.BooleanField(default=False)),
                ('telemarketing', models.BooleanField(default=False)),
                ('nova_contratacao', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
