# Generated by Django 5.2.5 on 2025-08-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='desligamento',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='desligamentos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='admissao',
            field=models.DateField(verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='area_atuacao',
            field=models.CharField(max_length=100, verbose_name='Área de atuação'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='bloco_pedido',
            field=models.BooleanField(default=False, verbose_name='Bloco Pedido'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='carregador_tablet',
            field=models.BooleanField(default=False, verbose_name='Carregador Tablet'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='carta_pedido_demissao',
            field=models.BooleanField(default=False, verbose_name='Carta Pedido Demissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='catalogo',
            field=models.BooleanField(default=False, verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='chip_dados',
            field=models.BooleanField(default=False, verbose_name='Chip Dados'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='chip_voz',
            field=models.BooleanField(default=False, verbose_name='Chip Voz'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='data_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de registro'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='demissao',
            field=models.DateField(verbose_name='Data de demissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='fardamento',
            field=models.BooleanField(default=False, verbose_name='Fardamento'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='fone_tablet',
            field=models.BooleanField(default=False, verbose_name='Fone Tablet'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='nova_contratacao',
            field=models.BooleanField(default=False, verbose_name='Previsão de nova contratação?'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='relatorio_inadimplencia',
            field=models.BooleanField(default=False, verbose_name='Relatório de Inadimplência'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='substituto',
            field=models.BooleanField(default=False, verbose_name='Há substituto em seleção?'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='supervisor',
            field=models.CharField(max_length=100, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='tablet',
            field=models.BooleanField(default=False, verbose_name='Tablet'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='telemarketing',
            field=models.BooleanField(default=False, verbose_name='Área liberada para telemarketing?'),
        ),
    ]
