# Generated by Django 5.2.5 on 2025-08-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_desligamento_criado_por_alter_desligamento_admissao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desligamento',
            options={'verbose_name': 'Desligamento', 'verbose_name_plural': 'Desligamentos'},
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='admissao',
            field=models.DateField(verbose_name='Admissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='area_atuacao',
            field=models.CharField(max_length=100, verbose_name='Área de Atuação'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='bloco_pedido',
            field=models.BooleanField(default=False, verbose_name='Bloco de Pedido'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='carregador_tablet',
            field=models.BooleanField(default=False, verbose_name='Carregador do Tablet'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='carta_pedido_demissao',
            field=models.BooleanField(default=False, verbose_name='Carta de Pedido de Demissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='chip_dados',
            field=models.BooleanField(default=False, verbose_name='Chip de Dados'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='chip_voz',
            field=models.BooleanField(default=False, verbose_name='Chip de Voz'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato Particular'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='data_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='demissao',
            field=models.DateField(verbose_name='Demissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='fone_tablet',
            field=models.BooleanField(default=False, verbose_name='Fone de Ouvido do Tablet'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Desligamento'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='nova_contratacao',
            field=models.BooleanField(default=False, verbose_name='Há previsão de nova contratação?'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='telemarketing',
            field=models.BooleanField(default=False, verbose_name='Área liberada para Telemarketing?'),
        ),
    ]
