# Generated by Django 5.2.5 on 2025-08-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_desligamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desligamento',
            name='supervisor',
        ),
    ]
