# Generated by Django 5.2.5 on 2025-08-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_remove_desligamento_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato Particular')),
                ('admissao', models.DateField(verbose_name='Data de Admissão')),
                ('area_atuacao', models.CharField(max_length=100, verbose_name='Área de Atuação')),
                ('documentos_entregues', models.BooleanField(default=False, verbose_name='Documentos entregues')),
                ('treinamento', models.BooleanField(default=False, verbose_name='Treinamento inicial realizado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Admissão',
                'verbose_name_plural': 'Admissões',
            },
        ),
        migrations.CreateModel(
            name='Distrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo do Distrato')),
                ('data_distrato', models.DateField(verbose_name='Data do Distrato')),
                ('negociado', models.BooleanField(default=False, verbose_name='Distrato negociado?')),
                ('multa_aplicada', models.BooleanField(default=False, verbose_name='Houve multa contratual?')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Distrato',
                'verbose_name_plural': 'Distratos',
            },
        ),
    ]
