# Generated by Django 5.2.5 on 2025-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_admissao_distrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissao',
            name='admissao',
        ),
        migrations.RemoveField(
            model_name='admissao',
            name='area_atuacao',
        ),
        migrations.RemoveField(
            model_name='admissao',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='admissao',
            name='documentos_entregues',
        ),
        migrations.RemoveField(
            model_name='admissao',
            name='treinamento',
        ),
        migrations.AddField(
            model_name='admissao',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo a Ocupiar'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='conta_gov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta Gov'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='coordenador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão RG'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='fone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='operacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='orgao_exp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pai'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='senha_gov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha Gov'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='substituicao',
            field=models.BooleanField(default=False, verbose_name='É substituição?'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='supervisor_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor Responsável'),
        ),
        migrations.AddField(
            model_name='admissao',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código RCA'),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
