# Generated by Django 5.2.5 on 2025-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_remove_admissao_admissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrato',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='data_distrato',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='multa_aplicada',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='negociado',
        ),
        migrations.AddField(
            model_name='distrato',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bônus'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='comissao_mes_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comissão do Mês Corrente'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='comissoes_bloqueadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comissões Bloqueadas'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='descontos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descontos / Empréstimos / Vales'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='dias_trabalhados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Trabalhados'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='gratificacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gratificação e Outros'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='indenizacao_1_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indenização 1/12 avos'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='indenizacao_1_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indenização 1/3'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='meses_trabalhados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses Trabalhados'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='operacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='periodo_anos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Período em Anos'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='total_geral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Geral - Comissão período trabalhado'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='total_ultimos_3_meses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Comissão últimos 3 meses'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='valor_rescisao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Rescisão'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Representante'),
        ),
    ]
