# Generated by Django 5.2.5 on 2025-08-27 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_remove_distrato_codigo_remove_distrato_data_distrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrato',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='Conta Corrente'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='operacao',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='titular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titular'),
        ),
    ]
