# Generated by Django 5.2.5 on 2025-08-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_alter_distrato_agencia_alter_distrato_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desligamento',
            name='observacoes',
        ),
    ]
