# Generated by Django 5.2.5 on 2025-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_remove_desligamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='desligamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
