# Generated by Django 4.2.16 on 2025-09-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0010_desligamento_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desligamento',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='admissao',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo a Ocupar'),
        ),
        migrations.CreateModel(
            name='Hierarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordena', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisionado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hierarquia (Coordenador -> Supervisor)',
                'verbose_name_plural': 'Hierarquias (Coordenador -> Supervisores)',
                'unique_together': {('coordenador', 'supervisor')},
            },
        ),
    ]
