# Generated by Django 4.2.16 on 2025-09-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0011_remove_desligamento_observacoes_alter_admissao_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarquia',
            options={'verbose_name': 'Hierarquia', 'verbose_name_plural': 'Hierarquias'},
        ),
    
        migrations.RemoveField(
            model_name='distrato',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='comissao_mes_corrente',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='comissoes_bloqueadas',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='descontos',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='dias_trabalhados',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='gratificacao',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='indenizacao_1_12',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='indenizacao_1_3',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='meses_trabalhados',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='periodo_anos',
        ),
        migrations.RemoveField(
            model_name='distrato',
            name='valor_rescisao',
        ),
        migrations.AlterField(
            model_name='admissao',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código RCA'),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='admissao',
            name='senha_gov',
            field=models.CharField(blank=True, help_text='⚠️ Não recomendado salvar senha em texto puro', max_length=100, null=True, verbose_name='Senha Gov (NÃO armazenar em produção)'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Admissão'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Demissão'),
        ),
        migrations.AlterField(
            model_name='hierarquia',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hierarquia',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
