# Generated by Django 4.2.16 on 2025-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_alter_hierarquia_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hierarquia',
            unique_together=set(),
        ),
    ]
