# Generated by Django 4.2.16 on 2025-09-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_create_hierarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='desligamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
