# Generated by Django 4.2.16 on 2025-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_admissao_status_desligamento_status_distrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('troca', 'Troca')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Desligamento ( Se for trocar de rota, colocar o novo código)'),
        ),
        migrations.AlterField(
            model_name='desligamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('troca', 'Troca')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('troca', 'Troca')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
