# Generated by Django 4.2.16 on 2025-09-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_alter_admissao_status_alter_desligamento_motivo_and_more'),
        ('rh', '0017_alter_codigo_fields'),
    ]

    operations = [
    ]
